### PR TITLE
Major improvements made by Wu Zhongfu.

### PR DESCRIPTION
**Pull request by spm2020spring**
- Now the administrator can create second-level subject.

- Now the administrator can hide articles.

- Revised database tables according to http://lanlab.org/course/2020f/ooad/hui-database-schema.svg

- Improved character encoding such that we can display Chinese characters properly.

### CODE REVIEW

**Comment by spm2020spring** [comment]
@MrWuZhongFu Why could not I post the following comment to this [article](http://47.115.56.157:8080/wzf/Controller?page=view-article&title=Naive%20Bayes)?

**This is a nice essay for understanding naive bayes.  Better than any textbook. -Hui**

**Comment by spm2020spring** [comment]
@MrWuZhongFu Why is **Popularity** not a number on[ this page](http://47.115.56.157:8080/wzf/Controller?page=subject&id=Machine%20Learning)?

**Comment by spm2020spring** [comment]
@MrWuZhongFu Perhaps it is useful to ask people to enter their names while they are submitting an article.  Please add that.  Thanks.

-Hui

**Comment by MrWuZhongFu** [comment]
Teacher, for your three emails, I have carefully checked and solved the corresponding problems.&nbsp;
1、Comment, I limit 50&nbsp;characters&nbsp; before, because it is too long，some pages are ugly. Now I set the length of comments to 100. and if your comments are longer than 100 characters, there will be a notice. Thank you for finding this bug.&nbsp;
2、As you ask, need to add a name when publishing an article. I have already done it.&nbsp;
3、What's more, Isn't Popularity an improvement for us this semester? The last senior did not do this function. Now that you mentioned the Popularity I've already done it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Software Project Management"<notifications@github.com&gt;; 
发送时间: 2020年12月2日(星期三) 上午10:05
收件人: "lanlab-org/OAPS-Jifry"<OAPS-Jifry@noreply.github.com&gt;; 
抄送: "1614518467"<1614518467@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [lanlab-org/OAPS-Jifry] Major improvements made by Wu Zhongfu. (#8)





 
@MrWuZhongFu Why could not I post the following comment to this article?
 
This is a nice essay for understanding naive bayes.  Better than any textbook. -Hui

**Pull request merged**
